### ISSUE TITLE
报错：free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by Nooooooda** [YuzukiTsuru/AmiiboTap#2]
![image](https://user-images.githubusercontent.com/46375344/138273558-f832ab8d-5ada-4b7d-b525-d4f155282cc4.png)
报错后中断了

**Comment by Noda2333** [comment]
Windows10 21H1 使用 VMware Workstation 15 Pro 下的 Ubuntu 20.04.2 LTS 虚拟机，虚拟机通过 PL-2303 USB-to-Serial 连接PN532

**Comment by Noda2333** [comment]
使用 [pimiibo](https://github.com/Normola/pimiibo) 写入卡片成功了
